### ISSUE TITLE
Using a `Redirect` route breaks static build

### ISSUE THREAD

**Issue by medfreeman** [phenomic/phenomic#1093]
v1.0.0-alpha3

Given the following file:

`App.js`
```
import React from "react"
import { Router, Route, Redirect, browserHistory } from "react-router"
import { createApp, renderApp } from "@phenomic/preset-react-app/lib/client"

import Html from "./src/components/Layout/Html"
import ErrorPage from "./src/components/Templates/ErrorPage"
import BlogArchive from "./src/components/Templates/BlogArchive"
import BlogPost from "./src/components/Templates/BlogPost"

const routes = () => (
  <Router history={ browserHistory }>
    <Redirect from="/home" to="/" />
    <Route path="/" component={ Page } />
    <Route path="/blog/" component={ BlogArchive } />
    <Route path="/blog/after/:after" component={ BlogArchive } />
    <Route path="/blog/*" component={ BlogPost } collection="posts" />
    <Route path="*" component={ ErrorPage } />
  </Router>
)

export default createApp(routes, Html)

if (module.hot) {
  module.hot.accept(() => renderApp(routes))
}
```

Running `yarn build` yields:

```
/home/xx/dev/med/node_modules/@phenomic/plugin-renderer-react/lib/render/server.js:57
            containers = renderProps.components.filter(function (item) {
                                    ^
TypeError: Cannot read property 'components' of undefined
    at Object._callee$ (/home/xx/dev/med/node_modules/@phenomic/plugin-renderer-react/lib/render/server.js:57:37)
    at tryCatch (/home/xx/dev/med/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/xx/dev/med/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/xx/dev/med/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/xx/dev/med/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/xx/dev/med/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.
```
[Relevant line in source](https://github.com/phenomic/phenomic/blob/31cd99ef9c98291ff2640009a26dff73aab1ae7a/packages/plugin-renderer-react/src/render/server.js#L67)

**Comment by MoOx** [comment]
Looks like a bug. @bloodyowl could you take a look maybe?

**Comment by bloodyowl** [comment]
hum yeah, didn't actually implemented this.

for ghPages backend, we'll need to generate a JS redirect page. do you have any user in mind who uses a different backend to see if we need to use plugins for this to have proper `301` & `302`?

**Comment by bherila** [comment]
Idea: emit a `<meta>` based redirect which would work for static pages.

**Comment by btk** [comment]
@bherila that won't be a 301 redirect.

**Comment by MoOx** [comment]
meta redirect will be our first solution as it's considered as 301 by google (confirmed by a google team member somewhere on a google group).

**Comment by MoOx** [comment]
@bloodyowl maybe our first step is to avoid breaking the build and ignore first, then implement a html generation with a meta redirect. Note that we will have to somehow attach the redirect to a query if url contains a parameter.
