### ISSUE TITLE
Error: window is not defined while npm run build

### ISSUE THREAD

**Issue by sahil6111** [phenomic/phenomic#1101]
`/project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:69
      if (window.QUnit) {
^
ReferenceError: window is not defined
    at transitionEndTest (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:69:1)
    at setTransitionEndSupport (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:105:1)
    at /project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:124:1
    at Object.<anonymous> (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:127:4)
    at /project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:12:1
    at Object.<anonymous> (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/~/metismenu/dist/metisMenu.js:22:2)
    at Object.module.exports.s (/project-folder/node_modules/.cache/phenomic/webpack/phenomic.main.js:47294:30)
    at __webpack_require__ (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/webpack/bootstrap 37bcf374641a6479be76:19:1)
    at Object.module.exports.Object.defineProperty.value (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/App.js:6:1)
    at __webpack_require__ (/project-folder/node_modules/.cache/phenomic/webpack/webpack:/webpack/bootstrap 37bcf374641a6479be76:19:1)`

Getting above error when i run the **npm run build** command
Need help resolving it.

**Comment by MoOx** [comment]
If you are using v0.x, you should have a proper warning telling you what to do.
In short, you should not call a module that rely on window if window is undefined (and it's undefined for static rendering as rendering is not done in a browser).
