### ISSUE TITLE
Getting Started Example not Working with 1.0.0-alpha.10

### ISSUE THREAD

**Issue by benjaminshafii** [phenomic/phenomic#1170]
```
  cd phenomic
  rm package.json
  cd examples
  cd react-app-getting-started
  npm install
  npm start
```

Returns the following error

```
/home/benjaminshafii/phenomic/examples/react-app-getting-started/Html.js:4
import * as React from "react";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at loader (/home/benjaminshafii/phenomic/examples/react-app-getting-started/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/benjaminshafii/phenomic/examples/react-app-getting-started/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

**Comment by MoOx** [comment]
We use babel-register so we should not have this kind of issue... That's weird but it has been already reported by @ArthurClemens & @DominikGuzei on Gitter, not sure how they handled this.
Will have a look!

**Comment by MoOx** [comment]
Ok I know what's going on. We are currently not transpiling by default modules (as we only have a  webpack bundler plugin for now). This issue is not happening on our repo since we have a babel configuration that hide the problem. I am working on a fix!

**Comment by benjaminshafii** [comment]
That was fast!

**Comment by MoOx** [comment]
v1.0.0-alpha.11 is out!

**Comment by spacenate** [comment]
Awesome, thank you @MoOx! This also fixed an issue I had experienced while trying to add my own Html.js file (not when using the example, but rather using the @phenomic/preset-react-app getting started tutorial).
