### ISSUE TITLE
Error in watcher while editing a MD file

### ISSUE THREAD

**Issue by drazik** [phenomic/phenomic#1208]
Hello,

When I edit some markdown files and save them, I randomly get the following error : 

```
/home/drazik/workspace/blog/node_modules/@phenomic/core/lib/watch/index.js:120
      return file.name === filepath;
                  ^

TypeError: Cannot read property 'name' of undefined
    at /home/drazik/workspace/blog/node_modules/@phenomic/core/lib/watch/index.js:120:19
    at Array.find (native)
    at NodeWatcher.<anonymous> (/home/drazik/workspace/blog/node_modules/@phenomic/core/lib/watch/index.js:119:23)
    at NodeWatcher.emit (events.js:159:13)
    at NodeWatcher.rawEmitEvent (/home/drazik/workspace/blog/node_modules/sane/src/node_watcher.js:356:8)
    at NodeWatcher.<anonymous> (/home/drazik/workspace/blog/node_modules/sane/src/node_watcher.js:347:12)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
```

The phenomic version I use is `1.0.0-alpha.13`. And my node version is `9.2.0`.

It may be related to #1157 , but it is not really the same error.

**Comment by MoOx** [comment]
Looks like a bug. No way to reproduce with a hight percentage of failures?

**Comment by drazik** [comment]
Actually it seems to be related to Vim. I explain myself : 

In Vim, when I enter `:w` one time, there's no problem. But the second time, the error occurs.

In VS Code or in a random Linux text editor, there is absolutely no problem.

The only difference I know between Vim and others is that it writes some backup files when we save a file. I turned this off with `set nobackup` and `set nowritebackup`, and the error is gone.
