### ISSUE TITLE
How to add https://github.com/asfktz/autodll-webpack-plugin to webpack.config.js for faster dev and prod builds ??

### ISSUE THREAD

**Issue by iiitmanikanta** [phenomic/phenomic#1228]
for the large applications it took more than 2 mins. for updating live changes during development mode...how to reduce this latency.
i am trying to add this library to webpack config [Auto Dll](https://github.com/asfktz/autodll-webpack-plugin) but getting the errors like below

```
 Updating/Users/manikantak/Desktop/ibhubs.co/node_modules/webpack/lib/DelegatedModuleFactoryPlugin.js:43
                                if(request && request in this.options.content) {
                                                      ^

TypeError: Cannot use 'in' operator to search for './node_modules/webpack-hot-middleware/client.js' in undefined
    at DelegatedModuleFactoryPlugin.<anonymous> (/Users/manikantak/Desktop/ibhubs.co/node_modules/webpack/lib/DelegatedModuleFactoryPlugin.js:43:27)
    at NormalModuleFactory.applyPlugins [as applyPluginsWaterfall] (/Users/manikantak/Desktop/ibhubs.co/node_modules/tapable/lib/Tapable.js:37:47)
```

**Comment by MoOx** [comment]
You are probably using a version of this package that doesn't work current webpack version. Please share more information about version and config. The best thing would be to give us a repo to reproduce the error.
