### ISSUE TITLE
Error with oniguruma during installation of preset-react-app on MacOS with Nix and Yarn

### ISSUE THREAD

**Issue by rhokue** [phenomic/phenomic#1277]
Hello. First of all, thank you very much for this amazing project which is exactly what I have been looking for!

I'm currently trying to follow the [installation guide for preset-react-app](https://phenomic.io/en/packages/preset-react-app/docs/getting-started/01/). I ran:

```
$ yarn init
$ yarn add --dev react react-dom react-router @phenomic/core @phenomic/cli
```

Afterwards, when I run `yarn add --dev @phenomic/preset-react-app`, I get the following error:

```
$ yarn add --dev @phenomic/preset-react-app

yarn add v1.13.0
[1/4] 🔍  Resolving packages...
warning @phenomic/preset-react-app > @phenomic/plugin-transform-markdown > remark-highlights > highlights > season > cson-parser > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @phenomic/cli@1.0.0-beta.11" has unmet peer dependency "@babel/core@^7.0.0".
warning "@phenomic/cli > @babel/plugin-proposal-class-properties@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/plugin-proposal-object-rest-spread@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env@7.4.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/register@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.4.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@phenomic/cli > @babel/plugin-proposal-object-rest-spread > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-proposal-json-strings@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-syntax-async-generators@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-syntax-json-strings@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-async-to-generator@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-block-scoping@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-classes@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-computed-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-destructuring@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-dotall-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-duplicate-keys@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-for-of@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-function-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-modules-amd@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-modules-umd@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.4.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-new-target@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-object-super@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-parameters@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-regenerator@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-spread@7.2.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-template-literals@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.4.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-react > @babel/plugin-transform-react-display-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-react > @babel/plugin-transform-react-jsx@7.3.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-react > @babel/plugin-transform-react-jsx-self@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-react > @babel/plugin-transform-react-jsx-source@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/cli > @babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@phenomic/preset-react-app > @phenomic/plugin-renderer-react@1.0.0-beta.11" has incorrect peer dependency "react-router@^3.2.0".
[4/4] 🔨  Building fresh packages...
[-/2] ⠄ waiting...
error /Users/username/some/path/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/username/some/path/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gyp info spawn /Users/username/.nix-profile/bin/python2
gyp info spawn args [ '/nix/store/63f22xvg7zpvcab9q3y4d5qfdr4rsb3h-nodejs-10.15.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/username/some/path/node_modules/oniguruma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/nix/store/63f22xvg7zpvcab9q3y4d5qfdr4rsb3h-nodejs-10.15.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/username/.node-gyp/10.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/username/.node-gyp/10.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/nix/store/63f22xvg7zpvcab9q3y4d5qfdr4rsb3h-nodejs-10.15.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/username/.node-gyp/10.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/username/some/path/node_modules/oniguruma',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/Users/username/some/path/node_modules/oniguruma/build'
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
../deps/onig/enc/mktable.c: In Funktion »IsAlpha«:
../deps/onig/enc/mktable.c:251:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0xa3 || c == 0xb3) return 1;
        ^
../deps/onig/enc/mktable.c:253:3: Anmerkung: hier
   case KOI8:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsCntrl«:
../deps/onig/enc/mktable.c:321:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0xad) return 1;
        ^
../deps/onig/enc/mktable.c:323:3: Anmerkung: hier
   case ISO_8859_1:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsLower«:
../deps/onig/enc/mktable.c:551:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0xa3) return 1;
        ^
../deps/onig/enc/mktable.c:553:3: Anmerkung: hier
   case KOI8:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsPrint«:
../deps/onig/enc/mktable.c:574:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0x85) return 1;
        ^
../deps/onig/enc/mktable.c:576:3: Anmerkung: hier
   case ISO_8859_1:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsPunct«:
../deps/onig/enc/mktable.c:662:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0xad) return 1;
        ^
../deps/onig/enc/mktable.c:664:3: Anmerkung: hier
   case UNICODE_ISO_8859_1:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsSpace«:
../deps/onig/enc/mktable.c:751:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0x85) return 1;
        ^
../deps/onig/enc/mktable.c:753:3: Anmerkung: hier
   case ISO_8859_1:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsUpper«:
../deps/onig/enc/mktable.c:897:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0xb3) return 1;
        ^
../deps/onig/enc/mktable.c:899:3: Anmerkung: hier
   case KOI8:
   ^~~~
../deps/onig/enc/mktable.c: In Funktion »IsWord«:
../deps/onig/enc/mktable.c:1090:8: Warnung: diese Anweisung könnte durchfallen [-Wimplicit-fallthrough=]
     if (c == 0xa3 || c == 0xb3) return 1;
        ^
../deps/onig/enc/mktable.c:1092:3: Anmerkung: hier
   case KOI8:
   ^~~~
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  LIBTOOL-STATIC Release/oniguruma.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 243, in ExecFilterLibtool
    libtoolout = subprocess.Popen(cmd_list, stderr=subprocess.PIPE, env=env)
  File "/nix/store/ygmpj2k0c47xwpxa6pfvss7p1h70yjzs-python-2.7.15/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/nix/store/ygmpj2k0c47xwpxa6pfvss7p1h70yjzs-python-2.7.15/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [oniguruma.target.mk:202: Release/oniguruma.a] Error 1
make: Leaving directory '/Users/username/some/path/node_modules/oniguruma/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nix/store/63f22xvg7zpvcab9q3y4d5qfdr4rsb3h-nodejs-10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/nix/store/63f22xvg7zpvcab9q3y4d5qfdr4rsb3h-nodejs-10.15.0/bin/node" "/nix/store/63f22xvg7zpvcab9q3y4d5qfdr4rsb3h-nodejs-10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/some/path/node_modules/oniguruma
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

I am on Mac-OS, using nix package manager. What am I missing? Thanks in advance for your help.

**Comment by rhokue** [comment]
I guess, what I'm actually asking for is what the non-npm dependencies preset-react-app has.

**Comment by MoOx** [comment]
@rhokue none. Can you give more info about node/npm/yarn/macos?
The thing failing seems to be oniguruma, which is an npm dep that require native build (not sure what dep require this one...)

**Comment by rhokue** [comment]
Thanks, @MoOx!

Mac OS version is 10.14.3.

The last three lines in the posted error log contain:

```
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
```

But when I run `node --version` it returns `v8.15.0`. That's probably because the installation uses a different node-version than globally installed.

Yarn version is 1.13.0.

**Comment by MoOx** [comment]
> That's probably because the installation uses a different node-version than globally installed

That may be a reason for an error. Can you try to use a consistent version of node & see if the error is still here?

**Comment by rhokue** [comment]
Okay, I will try.

I also just tried out "npm i --save-dev" instead of "yarn add --dev". I got [this error log](http://sprunge.us/iTGtAj).

**Comment by rhokue** [comment]
@MoOx, I installed only that version of node globally which was used during the installation, that is 10.15.0. NPM has version 6.8.0 globally and during installation.

I also just did
```
rm -r *
echo '{"private":true}' > package.json
npm install --save-dev react react-dom react-router@^3.2.0 @phenomic/core @phenomic/cli
```

But when I do `npm install --save-dev @phenomic/preset-react-app`, I get these messages:

```
$ npm install --save-dev @phenomic/preset-react-app
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> fsevents@1.2.7 install /Users/username10/some/path/node_modules/fsevents
> node install


> oniguruma@7.0.2 install /Users/username10/some/path/node_modules/oniguruma
> node-gyp rebuild

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn sh ENOENT

npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh
npm ERR! oniguruma@7.0.2 install: `node-gyp rebuild`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the oniguruma@7.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username10/.npm/_logs/2019-03-25T14_06_43_371Z-debug.log
```

And [this is the log](http://sprunge.us/lmBr7T).

**Comment by rhokue** [comment]
Oh, sorry, my last post was trash. I had node-gyp uninstalled globally. I guess, I need it globally installed, right?

**Comment by MoOx** [comment]
You should NOT need anything globally installed. Global install are creating problems more than they solves...

**Comment by rhokue** [comment]
Hmm, sorry for bother you, @MoOx, with this oniguruma issue.

I installed bash node-gyp and bash globally. (The `sh` command was missing in PATH.)

When I try to install preset-react-app with npm, I get this [message](http://sprunge.us/MKeDIA) and this [error log](http://sprunge.us/8CUTuc).

When I try to add preset-react-app using yarn, I get [this output](http://sprunge.us/BTigLB).

As I said, Mac-OS version is 10.14.3. And:

```
$ uname -a
Darwin some-hostname 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
```

**Comment by MoOx** [comment]
Again, you should not install anything globally. node-gyp is used internally by module that have native modules.
I just tried a fresh install with node 10, latest npm & build is ok.
There is probably something wrong with your setup & I don't know what this is :/
Maybe check oniguruma issues

**Comment by rhokue** [comment]
Alright, thank you.

**Comment by rhokue** [comment]
I was able to successfully get started on plain NixOS/Linux (instead of MacOS).
