### ISSUE TITLE
Non ASCII characters in filenames break the build

### ISSUE THREAD

**Issue by gmarty** [phenomic/phenomic#878]
The build returns an error if you try to generate a file with non ASCII characters in the path. This minimal example:
```md
---
title: Japanese
route: 日本語.html
---
```
generates the following error message:
```bash
> phenomic build

ℹ Phenomic is starting +0.25s
✔ Copying assets +0.99s
✔ Building client files +13.44s
✔ Preparing static build +3.38s
✔ Building static files +0.21s
✖ Build failed
ReferenceError:

fetch is not defined

    at exports.default (~/simple-json-fetch/lib/index.js:10:1)
    at Object.get (~/phenomic/lib/redux/modules/pages.js:83:1)
    at Object.getPage (~/phenomic/lib/components/PageContainer/index.js:29:1)
    at PageContainer.preparePage (~/phenomic/lib/components/PageContainer/component.js:152:1)
    at PageContainer.componentWillMount (~/phenomic/lib/components/PageContainer/component.js:95:1)
    at ReactCompositeComponentWrapper.performInitialMount (~/react/lib/ReactCompositeComponent.js:350:1)
    at ReactCompositeComponentWrapper.mountComponent (~/react/lib/ReactCompositeComponent.js:257:1)
    at Object.mountComponent (~/react/lib/ReactReconciler.js:47:1)
    at ReactCompositeComponentWrapper.performInitialMount (~/react/lib/ReactCompositeComponent.js:370:1)
    at ReactCompositeComponentWrapper.mountComponent (~/react/lib/ReactCompositeComponent.js:257:1)
    at Object.mountComponent (~/react/lib/ReactReconciler.js:47:1)
    at ReactCompositeComponentWrapper.performInitialMount (~/react/lib/ReactCompositeComponent.js:370:1)
    at ReactCompositeComponentWrapper.mountComponent (~/react/lib/ReactCompositeComponent.js:257:1)
    at Object.mountComponent (~/react/lib/ReactReconciler.js:47:1)
    at ReactDOMComponent.mountChildren (~/react/lib/ReactMultiChild.js:240:1)
    at ReactDOMComponent._createContentMarkup (~/react/lib/ReactDOMComponent.js:661:1)[ truncated stack ]
```

**Comment by MoOx** [comment]
I think I have an idea why this trigger a "fetch" issue. Will have a look tonight.

**Comment by gmarty** [comment]
I can take a look if you point me in the right direction.

**Comment by MoOx** [comment]
It might be a bit tricky to fix, I am on it.

**Comment by MoOx** [comment]
@gmarty I will do more test about that.

**Comment by MoOx** [comment]
Probably fixed in v1.
