### ISSUE TITLE
Error: getaddrinfo ENOTFOUND myhost.local

### ISSUE THREAD

**Issue by seleckis** [phenomic/phenomic#998]
There is an option for package.js in [Documentation](https://phenomic.io/docs/usage/configuration/core/):
```
    // host for development
    "devHost": "0.0.0.0",
```
But when I change this to e.g. `myhost.local` and run `npm start`, I get an error:
```
$ npm start

> project@ start /Users/seleckis/Sites/project-folder
> phenomic start

/bin/sh: yarn: command not found
ℹ Phenomic is starting +0.23s
⠹ Updatingevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND myhost.local
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/seleckis/.nvm/versions/node/v6.6.0/bin/node" "/Users/seleckis/.nvm/versions/node/v6.6.0/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! project@ start: `phenomic start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project@ start script 'phenomic start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     phenomic start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/seleckis/Sites/project-folder/npm-debug.log
```
without this option enabled on `localhost` it works fine.

**Comment by MoOx** [comment]
No sure we can something else that is not an IP address.

**Comment by MoOx** [comment]
Probably not relevant with v1.
